spring:
  application:
    name: imms-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  datasource:
    # Use environment variables first, fallback to Supabase for prod
    url: ${DB_URL:jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
    username: ${DB_USER:postgres.iszmhcijlyovccybcbch}
    password: ${DB_PASS:"F*8vszP+*LZwCGh"}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "health"

# Cloudinary
cloudinary:
  cloud-name: di6r3oggs
  api-key: "624134459765584"
  api-secret: "Um6QoySn8er6aK5vm_0gWv5XB3I"

# --- DEVELOPMENT CONFIGURATION ---
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_DB_URL:jdbc:postgresql://localhost:5432/imms_db}
    username: ${DEV_DB_USER:postgres}
    password: ${DEV_DB_PASS:postgres}
  jpa:
    show-sql: true

